name: my_first_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.0
  file_picker: ^9.2.0
  cupertino_icons: ^1.0.8
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  provider: ^6.1.2
  lucide_icons: ^0.257.0
  fl_chart: ^0.70.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.1.11
  http_parser: ^4.1.2
  flutter_highlight: ^0.7.0
  collection: ^1.19.1
  flutter_markdown: ^0.7.6+2
  http: ^1.3.0
  intl: 0.19.0
  easy_localization: 3.0.7+1
  flutter_math_fork: ^0.7.3
  vapinew: ^0.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/LearnAbility.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/hi.json
    - assets/lang/en.json

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic

    - family: OpenDyslexicAlta
      fonts:
        - asset: assets/fonts/OpenDyslexicAlta-Regular.otf
        - asset: assets/fonts/OpenDyslexicAlta-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexicAlta-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexicAlta-BoldItalic.otf
          weight: 700
          style: italic

    - family: OpenDyslexicMono
      fonts:
        - asset: assets/fonts/OpenDyslexicMono-Regular.otf

flutter_localizations:
  sdk: flutter
